### ISSUE TITLE
kitchen-sync support

### ISSUE THREAD

**Issue by poelzi** [neillturner/kitchen-ansible#101]
kitchen-sync seems to monkeypatch only the chef_base class for better upload. it would be wonderful if kitchen-ansible would detect kitchen-sync and use the must faster transfer modes of those.

**Comment by poelzi** [comment]
It seems to be a change in newer kitchen releases. Just figured it out:
Add to .kitchen.yml
```yml
#<% require 'kitchen-sync' %>

transport:
  name: rsync
```

Add to Gemfile:
```ruby
gem 'kitchen-sync'
gem 'kitchen-transport-rsync'
```

works very much faster. will add it to my tips branch in the docs
