### ISSUE TITLE
UBUNTU: doesn't support 14.10 

### ISSUE THREAD

**Issue by v1v** [neillturner/kitchen-ansible#11]
It doesn't install ansible

```
: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-security/universe/binary-amd64/Packages  Hash Sum mismatch       
       
E:        Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree       
Reading state information... 1%
Reading state information... Done
       E: Unable to locate package ansible
```

.kitchen.yml
```yaml
---
driver:
  name: docker
  use_sudo: false
  ssh:
    pty: true
driver_config:
  hostname: kitchen
  socket: <%= ENV['DOCKER_HOST'] %>
provisioner:
  name: ansible_playbook
  roles_path: ../../
  hosts: localhost
  playbook: site.kitchen.yml
  require_ansible_repo: true
platforms:
  - name: ubuntu-14.10
suites:
- name: chef-client-sh
  extra_vars:
    type: sh
```

I've already forked your repo, I'll give a go if I can fix that issue.
