### ISSUE TITLE
Defining playbooks at the suite level

### ISSUE THREAD

**Issue by walterdolce** [neillturner/kitchen-ansible#127]
Hi. 
Is it possible to define playbooks on a suite basis?

I was trying to use the following with no success:
```
suites:
  - name: unique-setup
    playbook: './test/integration/unique-setup/cucumber/test-playbook.yml'
    run_list:
    attributes:
  - name: multiple-setup
    playbook: './test/integration/multiple-setup/cucumber/test-playbook.yml'
    run_list:
    attributes:
```

Thanks!

**Comment by rndmh3ro** [comment]
`playbook` is a provisioner option. Try this:
```
suites:
  - name: unique-setup
    provisioner:
      playbook: './test/integration/unique-setup/cucumber/test-playbook.yml'
  - name: multiple-setup
    provisioner:
      playbook: './test/integration/multiple-setup/cucumber/test-playbook.yml'
```
