### ISSUE TITLE
Automatically copy SSH keys to Ansible host

### ISSUE THREAD

**Issue by conorsch** [neillturner/kitchen-ansible#132]
Thanks for writing this, and especially for the recent integration of ansible_spec behavior for test discovery. Having a separate test VM dedicated to running Ansible makes it possible to test different Ansible versions across suites, and also ensures that the provisioning targets aren't contaminated with test-related packages.

The workflow in the docs works as described, but strikes me as a bit repetitious, particularly when destroying frequently. After every destroy, testers must manually copy keys around, and also look up the internal IP address if using DHCP for the internal network.

Worse, the proposed workflow doesn't scale to more than one provisioning target: Vagrant will automatically create a unique SSH key for each VM, but the proposed config only supports a single SSH key that's reused across hosts—so only one VM will accept logins, and the others will fail.

Locally, I've got a custom `Rakefile` that dynamically inters IP addresses and copies SSH keys into the Ansible host. There's a patch or two required to `lib/kitchen/provisioner/ansible_playbook.rb` to glue it all together.

Would you be interested in having these automation changes as part of `kitchen-ansible`? Would they be better placed as part of the `busser-ansiblespec` project?

**Comment by neillturner** [comment]
That would be great. I'm a big fan of MVP (minimum viable product) so i just knock out the ideas and see what happens. I've been very lucky to get lots of contributions for kitchen-ansible often from people clever than me. I've also got a day job as a devops consultant so i have limited time but at least i have real world experience. -) 

 I actually expect people to use this mostly with clouds like AWS (I do most of my work with AWS) rather than vagrant but having a better vagrant solution would be very useful. 
So what would be good is something that could put the ssh keys into the ansible server that come from anywhere be in vagrant, AWS or whatever and support multiple servers. 
 Maybe it is a two part thing. 
 1. copy ssh key build by vagrant to a location. 
 2. in kitchen-ansible have a parameter say ssh_key_directory when we put all the the ssh keys and they are copied to the ansible box. Then they could be referenced in the hosts file maybe?  
I'm not sure if a Rakefile is a great implementation but i'll look at anything. 
 Anyway you have highlighted what the workflow should be. 
  1. create the servers that are to be provisioned in vagrant AWS oe whatever. 
  2. copy the ssh keys for them somewhere
  3. create the server to run ansible in vagrant or whatever.
  4. automatically copy the ssh keys to the ansible server and run the converge   

 I'm also working on windows support so the ansible linux server will be able to use winrm to access windows servers and even be able to have a mixture of windows and linux servers. 

 I'm expect the code needs to be in kitchen-ansible as the ssh keys are needed to do the converge and then the busser-ansiblespec can have some config to get the ssh keys from where we put them in ansible. 

thanks for your feedback and what be grateful for any input you can give.

**Comment by conorsch** [comment]
> I actually expect people to use this mostly with clouds like AWS (I do most of my work with AWS) rather than vagrant but having a better vagrant solution would be very useful. 

That's good to know—I should test that workflow more. Overall I find myself using test-kitchen almost exclusively with the VirtualBox or Docker drivers, deferring to more prod-like tools for testing against cloud providers. Will try out the AWS workflow and see how that feels—but you're correct that the changes I'm proposing are mostly for VirtualBox. I don't care for the prospect of copying my SSH private key up onto a cloud server to connect to other cloud servers, but that's what IAM is for.

> 1. copy ssh key build by vagrant to a location.
> 2. in kitchen-ansible have a parameter say ssh_key_directory when we put all the the ssh keys and they are copied to the ansible box. Then they could be referenced in the hosts file maybe?

That is exactly the implementation I'm using locally. For the `destroy` task, there's a monkeypatch on the Vagrant driver to make sure the SSH key for the associated host is cleaned up. For cases when the driver isn't Vagrant/VirtualBox, it should be enough to check the `ansible_playbook` provisioner block for one of two options that indicate whether the SSH key is shared or unique per-host.

```
provisioner:
  name: ansible_playbook
  roles_path: roles
  ansible_connection: ssh
  playbook: examples/default.yml
  ansible_host_key_checking: false
  ansible_verbosity: 2
  ansible_sudo: false

# Generate the INI-style hosts file, including inventory vars for SSH keyfiles unique per host.
# The rake file also copies the the unique keys into `.kitchen/ssh_keys/<hostname>`.
# May warrant a rename such as `ansible_infer_local_ips: yes`.
  ansible_inventory_file_generate_command: rake geninv

# Make sure the unique SSH keys are copied to the Ansible controller prior to converging:
  additional_copy_path: 
    - .kitchen/ssh_keys/
```

That example will perform the automatic key copying. If the `private_key: spec/tomcat_private_key.pem` line is present, however, that should override the key copying and use the one key for each host. Then we'd have both uses covered.

So far most of the logic for fetching the IPs is sandwiched into the `Rakefile`, but I can work on breaking that out and integrating it with the kitchen-ansible code. I'll work on that, with the eventual goal of integrating test discovery via busser-ansiblespec as well.
