### ISSUE TITLE
Does the AWS provisioner work?

### ISSUE THREAD

**Issue by artburkart** [neillturner/kitchen-ansible#142]
I have a config block that looks like this:

```yaml
platforms:
  - name: test-kitchen
    driver_config:
      provider: aws
      box: my_base_box
      username: ubuntu
      customize:
        access_key_id: "ACCESS_KEY"
        secret_access_key: "SECRET_ACCESS_KEY"
        ami: ami-########
        instance_type: m3.medium
        keypair_name: launcher
        iam_instance_profile_name: test-kitchen
        subnet_id: subnet-########
        associate_public_ip: true
        region: us-east-1
        security_groups:
          - sg-########
        availability_zone: us-east-1e
        tags:
          Name: test-kitchen
```

And I get this error:

```console
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --no-provision --provider aws ----
STDOUT:
STDERR: There are errors in the configuration of this machine. Please fix
the following errors and try again:

AWS Provider:
* A secret access key is required via "secret_access_key"
* An AMI must be configured via "ami" (region: #{region})
---- End output of vagrant up --no-provision --provider aws ----
Ran vagrant up --no-provision --provider aws returned 1]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

Is there anything I can do to salvage this? Cheers.
