### ISSUE TITLE
Rake dependency not being installed

### ISSUE THREAD

**Issue by alexharv074** [neillturner/kitchen-ansible#164]
I don't know which component has the bug or if it's my config but I'm getting this:

```
-----> Installing Serverspec..
Fetching: rspec-support-3.4.1.gem (100%)
Fetching: rspec-core-3.4.4.gem (100%)
Fetching: diff-lcs-1.2.5.gem (100%)
Fetching: rspec-expectations-3.4.0.gem (100%)
Fetching: rspec-mocks-3.4.1.gem (100%)
Fetching: rspec-3.4.0.gem (100%)
Fetching: rspec-its-1.2.0.gem (100%)
Fetching: multi_json-1.12.1.gem (100%)
Fetching: net-ssh-3.1.1.gem (100%)
Fetching: net-scp-1.2.1.gem (100%)
Fetching: net-telnet-0.1.1.gem (100%)
Fetching: sfl-2.2.gem (100%)
Fetching: specinfra-2.57.4.gem (100%)
Fetching: serverspec-2.36.0.gem (100%)
-----> serverspec installed (version 2.36.0)
       /opt/rh/ruby200/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rake (LoadError)
       	from /opt/rh/ruby200/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
       	from /tmp/verifier/gems/gems/busser-serverspec-0.5.9/lib/busser/runner_plugin/../serverspec/runner.rb:20:in `<main>'
       !!!!!! Ruby Script [/tmp/verifier/gems/gems/busser-serverspec-0.5.9/lib/busser/runner_plugin/../serverspec/runner.rb /tmp/verifier/suites/serverspec] exit code was 1
>>>>>> Verify failed on instance <default-centos-72>.
>>>>>> Please see .kitchen/logs/default-centos-72.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c '

BUSSER_ROOT="/tmp/verifier"; export BUSSER_ROOT
GEM_HOME="/tmp/verifier/gems"; export GEM_HOME
GEM_PATH="/tmp/verifier/gems"; export GEM_PATH
GEM_CACHE="/tmp/verifier/gems/cache"; export GEM_CACHE

sudo -E /tmp/verifier/bin/busser test
']
>>>>>> ----------------------
```

My `.kitchen.yml`:

```yaml
---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  ansible_verbose: false
  ansible_verbosity: 2
  require_ansible_repo: false
  require_ansible_omnibus: true
  require_chef_for_busser: false
  require_ruby_for_busser: true

verifier:
  name: Busser
  plugin:
    - Ansiblespec
  ruby_bindir: '/usr/bin'

platforms:
  - name: centos-7.2

suites:
  - name: default
```

My bundle:

```
$ bundle show 
Gems included by the bundle:
  * artifactory (2.3.2)
  * backticks (0.4.0)
  * bundler (1.10.5)
  * docker (0.3.1)
  * faraday (0.9.2)
  * highline (1.7.8)
  * kitchen-ansible (0.42.4)
  * kitchen-docker (2.4.0)
  * librarian (0.1.2)
  * librarian-ansible (3.0.0)
  * mixlib-install (1.0.11)
  * mixlib-shellout (2.2.6)
  * mixlib-versioning (1.1.0)
  * multipart-post (2.0.0)
  * net-scp (1.2.1)
  * net-ssh (3.1.1)
  * rake (11.1.2)
  * safe_yaml (1.0.4)
  * test-kitchen (1.8.0)
  * thor (0.19.1)
```

I'm about to investigate kitchen-verifier-serverspec but would be good to understand why the present config isn't working.
