### ISSUE TITLE
ansible_version ignored if Ansible already in docker container

### ISSUE THREAD

**Issue by alexharv074** [neillturner/kitchen-ansible#171]
It appears that if the provisioned Docker container already contains Ansible, the `ansible_version` flag is ignored:

My `.kitchen.yml`:

```yaml
---
driver:
  name: docker

platforms:
  - name: centos-7.2
    driver_config:
      image: ansible/centos7-ansible:stable
      platform: centos
      provision_command:
        - yum -y install iproute
        - yum -y install net-tools
      forward:
        - 8082:8082

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  ansible_verbose: false
  ansible_verbosity: 2
  require_ansible_repo: false
  require_ansible_omnibus: true
  ansible_version: 1.9.6
  require_chef_for_busser: false
  requirements_path: requirements.yml
  extra_vars:
    java_packages: ['java-1.8.0-openjdk']

verifier:
  name: serverspec

suites:
  - name: default
    verifier:
      patterns:
        - roles/ansible-nexus/test/integration/default/serverspec/default_spec.rb
      bundler_path: '/usr/local/bin'
      rspec_path: '/usr/local/bin'
```
