### ISSUE TITLE
Support for Ansible tags

### ISSUE THREAD

**Issue by metmajer** [neillturner/kitchen-ansible#20]
Hi - thanks for providing this awesome Ansible provisioner!

As an improvement I suggest to support a 'tags' attribute for the provisioner and a suite which could greatly facilitate the configuration of various test suites (since it only requires a single playbook) like so:

```
provisioner:
  name: ansible_playbook
  ...

suites:
 - name: default
   tags: [apache-httpd, apache-tomcat]

- name: apache-httpd
  tags: [apache-httpd]

- name: apache-tomcat
  tags: [apache-tomcat]
```

Best, Martin
