### ISSUE TITLE
additional_copy_path breaks jinja includes

### ISSUE THREAD

**Issue by boernd** [neillturner/kitchen-ansible#203]
As soon as I add the additional_copy_path property in one of my suites, includes in jinja templates throw errors. 

Suite example:
```
...
suites:
name: test
    - provisioner:
      playbook: playbooks/test.yml
      additional_copy_path: [ playbooks/test2.yml ]
      hosts: test
    driver_config:
      hostname: test
      instance_name: test
...
```

The test.yml playbook includes a test role which templates a file:
`{% include "testfile" %}`

`kitchen setup test` causes the following error:
```
      TASK [test : template test] ****************************************************
       fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "IOError: [Errno 20] Not a directory: '/tmp/kitchen/test2.yml/testfile'"}
```
Using recursive_additional_copy_path instead resolves the issue (/tmp/kitchen/test2.yml is not prefixed).
