### ISSUE TITLE
Override variables in kitchen.yml file

### ISSUE THREAD

**Issue by wasimkham** [neillturner/kitchen-ansible#213]
I've used Kitchen with Chef before and I can override attributes in the `suites` section like so:

```
suites:
  - name: default
    attributes:
      default:
        domain: domain.dev
```

I have all my ansible vars in `group_vars/all.yml` and I've tried different combinations of settings to override them but cannot figure it out. Is this even possible?

**Comment by wasimkham** [comment]
I have found a solution. It involves writing the vars in `tests/integration/<< suite >>/default.yml` like so:

```
- hosts: all
  vars:
    domain: domain.dev
  roles:
    - common
    - php
```
