### ISSUE TITLE
Vault password file isn't found

### ISSUE THREAD

**Issue by wasimkham** [neillturner/kitchen-ansible#214]
I specify my ansible vault password file in `ansible.cfg`

```
vault_password_file = ~/.vault_pass
```

This doesn't work when running ansible in test kitchen as it tries to find the vault password file on the vagrant machine. The converge fails with the following error:

```
ERROR! The vault password file /home/vagrant/.vault_pass was not found
```

I've tried to see if I can copy the file to the vagrant machine upon provision, I tried something like this in the `kitchen.yml`:

```
platforms:
  - name: ubuntu-14.04
    driver:
      provision:
        - ["file", "source: \"~/.vault_pass\"", "destination: \"~/.vault_pass\""]
      synced_folders:
        - ["../web", "/var/www/web", "create: true"]
```

Which I would hope that would create a line in the Vagrantfile like this:

```
  c.vm.provision "file", source: "~/.vault_pass", destination: "~/.vault_pass"
```

But this doesn't work. Any idea to get around the vault file problem?

**Comment by neillturner** [comment]
try adding -l debug to the kitchen command to get debug output to see what is happening. 

test kitchen copies the files to the vagrant machine to /tmp/kitchen and then runs. 
 
1. The vault password file needs to be copied. Perhaps to can use the  parameter 
  additional_copy_path
to point to a directory that will contain the vault password file. 

2. When ansible runs on the vagrant server the vault_password_file needs to be at  ~/.vault_pass. 
but you may be able to override that via an environment variable for the ansible command so it points to 
/tmp/kitchen/directorycontainvallypass/.valut_pass

**Comment by wasimkham** [comment]
Thanks @neillturner I haven't tried it yet but will give it go. Appreciate it.

**Comment by neillturner** [comment]
closing this as no more activity. will re-open if i get anymore activity.

**Comment by Demonsthere** [comment]
Hey there, I have the same problem with the vault password. Could you provide an example for additional_copy_path? What would be the correct syntax?

**Comment by wasimkham** [comment]
@Demonsthere You should be able to use the `ansible_vault_password_file: .vault_pass` option now in your `kitchen.yml` file. Here's my example:

```
---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: ansible_playbook
  roles_path: roles
  require_ansible_repo: true
  ansible_verbose: false
  ansible_version: latest
  ansible_vault_password_file: .vault_pass
  group_vars_path: group_vars_dev
```
