### ISSUE TITLE
Windows VM fails to create 

### ISSUE THREAD

**Issue by damacus** [neillturner/kitchen-ansible#215]
I get the following error when provisioning a Windows box: 
```
       Installing ansible, will try to determine platform os
$$$$$$ A parameter cannot be found that matches parameter name 'rf'.
At line:1 char:4
$$$$$$ + rm -rf $env:TEMP\kitchen/modules $env:TEMP\kitchen/roles $env:TEMP\kitchen/group ...
$$$$$$ +    ~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-Item], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
Parameter cannot be processed because the parameter name 'p' is ambiguous. Possible matches include: -Path -PipelineVariable.
At line:1 char:122
$$$$$$ + ... st_vars; mkdir -p $env:TEMP\kitchen
$$$$$$ +                    ~~
    + CategoryInfo          : InvalidArgument: (:) [mkdir], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameter,mkdir
```

It looks like it's this line causing the problem. 
https://github.com/neillturner/kitchen-ansible/blob/master/lib/kitchen/provisioner/ansible_playbook.rb#L243

**Comment by neillturner** [comment]
try setting the parameter 
  ansible_platform
to 
 windows 
in the kitchen.yml file
I don't think the code can determine it is windows only what the linux platform. I guess I need to change the docs to reflect this.

**Comment by damacus** [comment]
I've got the following config but it looks like it still doesn't pick up the correct platform. 
```
---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  roles_path: roles
  hosts: all
  ansible_verbose: true
  ansible_version: latest
  ansible_connection: winrm
  require_chef_omnibus: false
  require_chef_for_busser: false

transport:
  name: winrm
  winrm_transport: negotiate

platforms:
  - name: "ubuntu-14.04"
  - name: "centos-7.2"
  - name: "windows2012r2"
    driver:
      box: opentable/win-2012r2-standard-amd64-nocm
      ansible_connection: winrm
      ansible_platform: windows
      require_windows_support: true
      communicator: winrm
      provision: true
    transport:
      name: winrm
      winrm_transport: negotiate

suites:
  - name: default
    provisioner:
      playbook: role.yml

verifier: inspec

```

**Comment by neillturner** [comment]
remove 
    - name: "ubuntu-14.04"
  - name: "centos-7.2"
to simplify
what kitchen command are you using?

**Comment by damacus** [comment]
Latest yaml
```
---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: all
  ansible_verbose: true
  ansible_version: latest
  require_chef_omnibus: false
  require_chef_for_busser: false
  additional_copy_path:
    - "."

platforms:

  - name: "windows2012r2"
    driver:
      box: opentable/win-2012r2-standard-amd64-nocm
      ansible_connection: winrm
      ansible_platform: windows
      require_windows_support: true
      communicator: winrm
      provision: true
    transport:
      name: winrm
      winrm_transport: negotiate

suites:
  - name: default
    provisioner:
      playbook: role.yml

verifier: inspec
```

I'm doing 
- `kitchen create` 
- `kitchen converge` 
- Failure
