### ISSUE TITLE
Noisy converge

### ISSUE THREAD

**Issue by matschaffer** [neillturner/kitchen-ansible#220]
Just trying this out with the latest version from rubyforge (0.40.1) and the output seems fairly noisy.

```
       Preparing files for transfer
       Preparing playbook
       Preparing inventory
       Preparing modules
       nothing to do for modules
       Preparing roles
       Preparing ansible.cfg file
       Empty ansible.cfg generated
       Preparing group_vars
       nothing to do for group_vars
       Preparing additional_copy_path
       Preparing host_vars
       nothing to do for host_vars
       Preparing hosts file
       Preparing spec
       nothing to do for spec
       Preparing library plugins
       nothing to do for library plugins
       Preparing callback plugins
       nothing to do for callback plugins
       Preparing filter_plugins
       nothing to do for filter_plugins
       Preparing lookup_plugins
       nothing to do for lookup_plugins
       Finished Preparing files for transfer
       Installing ansible, will try to determine platform os
       Going to install ansible with:
            if [ ! $(which ansible) ]; then
              if [ -f /etc/centos-release ] || [ -f /etc/redhat-release ]; then
                if ! [ grep -q 'Amazon Linux' /etc/system-release ]; then

            if [ ! $(which ansible) ]; then
```

Is there a good way to quiet that down?

Here's my kitchen.yml incase I'm missing some option that might help.

```
---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: test-kitchen

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    provisioner:
      playbook: test/integration/default/playbook.yml
```

Thanks!
