### ISSUE TITLE
Ability to specify a vault encrypted extra_vars file

### ISSUE THREAD

**Issue by StFS** [neillturner/kitchen-ansible#224]
Hi.

I'm trying to figure out how to store some sensitive data (passwords etc.) and supplying it to kitchen at runtime.

At first we added a vault encrypted vars file to the role itself. This works but the problem is that the secrets we're storing are actually not something we want to share. For example, we are storing passwords to Docker Hub and we want each developer to supply their own credentials when they run kitchen.

This also rules out supplying them as part of extra_vars in the .kitchen.yml file.

I took a look at the code for kitchen-ansible and it seems that the extra_vars values are being supplied to ansible-playbook as the "-e" parameter. That parameter can take a reference to a file ("-e @some_file.yml") but when I tried that, I just got an error. Besides, I would like to specify some variables in plain text in the .kitchen.yml file and only supply the secret stuff from a vault encrypted file. The ansible-playbook can get multiple -e parameters where one is a list of key=value but another is a reference to a file but this is difficult to do it seems from .kitchen.yml (and as mentioned before, references to files don't seem to work anyways).

So I'm wondering if there is any way for me to specify some file (preferably vault encrypted) on the command line that kitchen would read, decrypt and add the variables defined within it to the run?

**Comment by neillturner** [comment]
1. env variable are test values so they could be a file now. 
see line 
  config[:env_vars].map { |k, v| "#{k}=#{v}" }.join(' ')
maybe you need a quote wrapped around the value? 
  config[:env_vars].map { |k, v| "#{k}='#{v}'" }.join(' ')
if i get more info on why your env var setting is failing then maybe i can fix/enhance 

2. Another possibility is to use a a custom_pre_play_comand
in my kitchen-puppet provisioner 
see https://github.com/neillturner/kitchen-puppet/blob/master/provisioner_options.md
i have some parameters to allow extra customization 
custom_pre_apply_command	nil	Custom shell command to be used before the puppet apply stage. Can be multiline. See examples below.
something similar to these can be added to the kitchen-ansible provisioner very easily. 

so if its possible to create a custom_command to do what you need before running ansible this we could add the  custom_pre_play_comand

**Comment by StFS** [comment]
That's great! Wow... and you have that version published already! Pretty awesome! Thanks!

**Comment by StFS** [comment]
Ok, so I just tried this and it wasn't working for me... so I looked at the code.

What I was hoping for was to be able to specify _both_ `extra_vars` and `extra_vars_file`.

This is supported by the `ansible-playbook` cli tool as it supports multiple `-e` arguments.

So while I'm at it, I would want to be able to specify both _and_ I would like to be able to specify multiple files as well (so I guess it would be better to call it `extra_vars_files` then).

I might try to make a pull request for this change if I find some time but it probably won't be until next week at the earliest.

**Comment by neillturner** [comment]
ok i didn't think of that. -)  its an  easy change though. create a pull or i will quickly do on the weekend.

**Comment by StFS** [comment]
that sounds fantastic!

**Comment by neillturner** [comment]
can specify bot extra_vars and extra_vars_file options in 0.46.1 so closing

**Comment by trinitronx** [comment]
I tested this with `additional_copy_path` also, and it worked!

```
provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  require_ansible_repo: true
  ansible_version: latest
  ansible_diff: true
  ansible_verbose: true
  ansible_verbosity: 2
  sudo: true
  ansible_vault_password_file: /Users/exampleuser/some/path/ansible-vault-test
  extra_vars_file: /tmp/kitchen/test_vault_secrets.yml
  additional_copy_path:
    - /Users/exampleuser/src/path/to/ansible-playbooks/playbooks/example/vars/test_vault_secrets.yml
  extra_vars:
    environment: test
```
Passing both `extra_vars_file`, and `extra_vars` works even with the hack-ish path `/tmp/kitchen`, because `additional_copy_path` can copy other files into `/tmp/kitchen` for you!

In this way, you can put `test_vault_secrets.yml` Ansible vault vars file outside of the role path you are testing too!  Of course, probably it's best practice to just include a special "test fixture" vars file (for testing purposes only) within the role directory you are running tests on.  But it's good to know this option exists for those special cases ;-)
