### ISSUE TITLE
ERROR! Unexpected Exception: 'Host' object has no attribute 'remove_group

### ISSUE THREAD

**Issue by ssirobertreilly** [neillturner/kitchen-ansible#227]
Hi, I am new to ansible but lots of experience with chef and test-kitchen. I get the following error 
```
Attempting to execute command - try 1 of 1.
D      [SSH] vagrant@127.0.0.1<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>"2200", :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :keys_only=>true, :keys=>["/Users/robert_reilly/ansible-test/.kitchen/kitchen-vagrant/kitchen-ansible-test-default-centos-72/.vagrant/machines/default/virtualbox/private_key"], :auth_methods=>["publickey"], :logger=>#<Logger:0x007fc5b290f310 @progname=nil, @level=4, @default_formatter=#<Logger::Formatter:0x007fc5b290f2e8 @datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0x007fc5b290f298 @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDERR>>, @mutex=#<Logger::LogDevice::LogDeviceMutex:0x007fc5b290f270 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x007fc5b290f220>>>>, :password_prompt=>#<Net::SSH::Prompt:0x007fc5b290f1f8>, :user=>"vagrant"}> (

          ANSIBLE_ROLES_PATH=/tmp/kitchen/roles sudo -E -s  ansible-playbook -i /tmp/kitchen/hosts  -c local -M /tmp/kitchen/modules -v         /tmp/kitchen/nginx.yaml
)
       Using /etc/ansible/ansible.cfg as config file
       ERROR! Unexpected Exception: 'Host' object has no attribute 'remove_group'
       to see the full traceback, use -vvv
```
I did not get any hits on this from google re: ansible which is why I am asking here... 

.kitchen
```
---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  roles_path: roles
  require_ansible_repo: true
  ansible_verbose: true
  require_ansible_omnibus: true
  ansible_omnibus_url: https://raw.githubusercontent.com/neillturner/omnibus-ansible/master/ansible_install.sh
  playbook: playbooks/nginx.yaml
  hosts: default


platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
    attributes:
```

kitchen.log
[https://pastebin.com/z5vjNJBQ](url)
