### ISSUE TITLE
Can not decrypt ansible vault 

### ISSUE THREAD

**Issue by jedipunkz** [neillturner/kitchen-ansible#231]
I would like to deploy ansible role to test-kitchen container. I ues these software.

* test-kitchen
* docker
* kitchen-ansible
* kitchen-docker

I have these file tree.

```
.
├── .kitchen
├── .kitchen.local.yml
├── .kitchen.yml
├── .vault_pass     #<-- include plain text password
├── chefignore
├── group_vars_dev
│   ├── vars.yml   #<--- var file
│   └── vault.yml #<--- encrypted vault file
├── site.yml
```

group_vars_dev/vars.yml include this line.

```
rabbitmq_users: "{{ vault_rabbitmq_users }}"
```

decrypted vault file include these lines.

```
vault_rabbitmq_users:
  - user: rabbitmq
    password: rabbitmq-password
```

then I have this .kitchen.local.yml file

```
provisioner:
  name: ansible_playbook
  playbook: ./site.yml
  roles_path: ../../roles
  group_vars_path: group_vars_dev
  ansible_vault_password_file: .vault_pass
  hosts: kitchen-deploy
  ansible_platform: centos
  ansible_version: latest
  require_chef_for_busser: true
```

Then, I got this error.

```
       TASK [rabbitmq : add rabbitmq users] *******************************************
       fatal: [localhost]: FAILED! => {"failed": true, "msg": "'rabbitmq_users' is undefined"}
```

Any idea do you have?
