### ISSUE TITLE
Ansible installation gets stuck due to a prompt

### ISSUE THREAD

**Issue by walterdolce** [neillturner/kitchen-ansible#238]
Hi,

The Ansible installation gets stuck in a prompt with the following configuration. Please see below.

```
---
driver:
  name: vagrant
  provider: virtualbox

provisioner:
  name: ansible_playbook
  hosts: all
  ansible_vault_password_file: ./vault_passphrase_development
  ansible_verbosity: 4
  ansible_verbose: true
  require_chef_for_busser: false
  require_ruby_for_busser: false
  requirements_path: ./requirements.yml
  roles_path: ./roles

verifier:
  name: inspec

platforms:
  - name: debian
    driver:
      box: debian/jessie64
      box_version: 8.7.0

suites:
  - name: default
    provisioner:
      playbook: ./development-app-playbook.yml
```

Output is:
```

       Configuration file '/etc/ansible/ansible.cfg'
        ==> File on system created by you or by a script.
        ==> File also in package provided by package maintainer.
          What would you like to do about it ?  Your options are:
           Y or I  : install the package maintainer's version
           N or O  : keep your currently-installed version
             D     : show the differences between the versions
             Z     : start a shell to examine the situation
        The default action is to keep your current version.
```
