### ISSUE TITLE
Installing Ansible via PIP is not idempotent

### ISSUE THREAD

**Issue by walterdolce** [neillturner/kitchen-ansible#240]
Hi,
Assuming the following provisioner setup:
```
# .kitchen.yml
provisioner:
  name: ansible_playbook
  hosts: all
  ansible_vault_password_file: ./vault_passphrase_development
  ansible_verbosity: 4
  ansible_verbose: true
  ansible_version: latest
  require_ansible_repo: false
  require_chef_for_busser: false
  require_ruby_for_busser: false
  require_pip: true
  requirements_path: ./requirements.yml
  roles_path: ./roles
  additional_copy_role_path: true
  additional_copy_path:
    - ./group_vars
    - ./vault
    - ./vars
    - ./roles_external
```

Looks like Ansible gets pulled every time a converge happens.
```
# ...

Installing ansible through pip
Hit http://security.debian.org jessie/updates InRelease
Ign http://ftp.ua.debian.org jessie InRelease

# ...
```

Should it not be installed once?

Thank you.
