### ISSUE TITLE
Breaking change in 0.47.2: additional_copy_role_path 

### ISSUE THREAD

**Issue by walterdolce** [neillturner/kitchen-ansible#250]
Hi,

I upgraded from `0.46.2` to `0.47.2` and by doing so things broke with the following `.kitchen.yml` file:

```
---
transport:
  max_ssh_sessions: 6

driver:
  name: vagrant
  provider: virtualbox

provisioner:
  name: ansible_playbook
  hosts: all
  ansible_verbosity: 4
  ansible_verbose: true
  ansible_version: latest
  ansible_sudo: false
  require_ansible_repo: false
  require_chef_for_busser: false
  require_ruby_for_busser: false
  require_pip: true
  requirements_path: ./requirements.yml
  roles_path: ./roles
  additional_copy_role_path: true
  additional_copy_path:
    - ./playbooks
    - ./group_vars
    - ./vault
    - ./vars
    - ./roles_external

verifier:
  name: inspec

platforms:
  - name: debian
    driver:
      box: debian/jessie64
      box_version: 8.7.0

suites:
   # various suite definitions
```

Looks like the `additional_copy_role_path: true` is causing an issue there. Looks like the [changes made](https://github.com/neillturner/kitchen-ansible/compare/0.46.6...0.47.2#diff-98a7abb81560c8e2b896de4e7efb82caR882) break the configuration above. I had to remove the `additional_copy_role_path` parameter from the `.kitchen.yml` file to solve the problem.

BTW, please note the documentation is not clear on what value the `additional_copy_role_path` should be set to. It only defines a default value and a note. Not an actual explanation about the use of the variable.

Thank you.
