### ISSUE TITLE
Still having issues with spec, fixtures and symlinks  - `ignore_paths_from_root: true`

### ISSUE THREAD

**Issue by aaronlippold** [neillturner/kitchen-ansible#252]
I am having issues with coping symlink'd dirs being copied to hosts on the converge stage. I know this issues had been thought to have been addressed but the solutions I found in the issues and PRs do not seem to be addressing my issue. I was hoping we could look at it again and see if we could work out what is causing my issue.

The directory that is causing issues is my `inspec_profiles` directory inside the `spec/fixtures` directory which has symlinks to the above InSpec profile supporting Beaker. We are using both Beaker and Test Kitchen to support two teams working with the profile. 

`Error: ( short )`
```
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [No such file or directory @ rb_file_s_stat - /var/folders/c4/0vsc4qvj4358b8099_hvv0mh0000gn/T/default-centos-7-sandbox-20170719-75552-8qhg6y/spec/fixtures/inspec_profiles/CentOS-7-disa_stig] on default-centos-7
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```
`Diagnose:`
```
---
timestamp: 2017-07-19 14:37:20 UTC
kitchen_version: 1.16.0
plugins:
  driver:
    Vagrant:
      class: Kitchen::Driver::Vagrant
      version: 1.1.0
      api_version: 2
  provisioner:
    AnsiblePlaybook:
      class: Kitchen::Provisioner::AnsiblePlaybook
      version:
      api_version:
  transport:
    Ssh:
      class: Kitchen::Transport::Ssh
      version: 1.16.0
      api_version: 1
  verifier:
    Inspec:
      class: Kitchen::Verifier::Inspec
      version: 0.19.0
      api_version: 1
loader:
  process_erb: true
  process_local: true
  process_global: true
  global_config:
  project_config:
    filename: "/Users/aaronl/Desktop/hardening/aaronlippold/inspec_profiles/.kitchen.yml"
    raw_data:
      driver:
        name: vagrant
        customize:
          natdnsproxy1: 'on'
          natdnshostresolver1: 'on'
      provisioner:
        hosts: all
        name: ansible_playbook
        roles_path: spec/fixtures/kitchen/roles
        host_vars_path: "/tmp/kitchen/host_vars"
        role_name: rhel7-stig
        require_ruby_for_busser: false
        require_chef_for_busser: false
        require_ansible_repo: true
        ansible_verbose: true
        copy_symlinks: true
        additional_copy_role_path: true
        ansible_version: latest
        ansible_yum_repo: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        ansible_verbosity: 2
        additional_copy_path:
        - spec/fixtures/kitchen/roles/RHEL7-STIG/tasks
        - spec/fixtures/kitchen/roles/RHEL7-STIG/vars
        - spec/fixtures/inspec_profiles
        - spec/fixtures/inspec_profiles/CentOS-7-disa_stig
        - spec/fixtures/inspec_profiles/RedHat-7-disa_stig
        https_proxy:
      transport:
        max_ssh_sessions: 6
      verifier:
        name: inspec
        sudo: true
      platforms:
      - name: centos-7
        driver:
          box: centos/7
      suites:
      - name: default
        verifier:
          inspec_tests:
          - file:///Users/aaronl/Desktop/hardening/aaronlippold/inspec_profiles/profiles/disa_stig-rhel7-baseline
  local_config:
  combined_config:
    filename:
    raw_data:
      driver:
        name: vagrant
        customize:
          natdnsproxy1: 'on'
          natdnshostresolver1: 'on'
      provisioner:
        hosts: all
        name: ansible_playbook
        roles_path: spec/fixtures/kitchen/roles
        host_vars_path: "/tmp/kitchen/host_vars"
        role_name: rhel7-stig
        require_ruby_for_busser: false
        require_chef_for_busser: false
        require_ansible_repo: true
        ansible_verbose: true
        copy_symlinks: true
        additional_copy_role_path: true
        ansible_version: latest
        ansible_yum_repo: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        ansible_verbosity: 2
        additional_copy_path:
        - spec/fixtures/kitchen/roles/RHEL7-STIG/tasks
        - spec/fixtures/kitchen/roles/RHEL7-STIG/vars
        - spec/fixtures/inspec_profiles
        - spec/fixtures/inspec_profiles/CentOS-7-disa_stig
        - spec/fixtures/inspec_profiles/RedHat-7-disa_stig
        https_proxy:
      transport:
        max_ssh_sessions: 6
      verifier:
        name: inspec
        sudo: true
      platforms:
      - name: centos-7
        driver:
          box: centos/7
      suites:
      - name: default
        verifier:
          inspec_tests:
          - file:///Users/aaronl/Desktop/hardening/aaronlippold/inspec_profiles/profiles/disa_stig-rhel7-baseline
instances:
  default-centos-7:
    platform:
      os_type: unix
      shell_type: bourne
    state_file:
      hostname: 127.0.0.1
      last_action: create
      last_error: Errno::ENOENT
      port: '2222'
      ssh_key: "/Users/aaronl/Desktop/hardening/aaronlippold/inspec_profiles/.kitchen/kitchen-vagrant/kitchen-inspec_profiles-default-centos-7/.vagrant/machines/default/virtualbox/private_key"
      username: vagrant
    driver:
      boot_timeout:
      box: centos/7
      box_check_update:
      box_download_ca_cert:
      box_download_insecure:
      box_url:
      box_version:
      cache_directory: false
      cachier:
      customize:
        natdnsproxy1: 'on'
        natdnshostresolver1: 'on'
      gui:
      kitchen_cache_directory: "/Users/aaronl/.kitchen/cache"
      kitchen_root: "/Users/aaronl/Desktop/hardening/aaronlippold/inspec_profiles"
      linked_clone:
      log_level: :info
      name: vagrant
      network: []
      pre_create_command:
      provider: virtualbox
      provision: false
      ssh: {}
      synced_folders: []
      test_base_path: "/Users/aaronl/Desktop/hardening/aaronlippold/inspec_profiles/test/integration"
      vagrant_binary: vagrant
      vagrantfile_erb: "/usr/local/lib/ruby/gems/2.4.0/gems/kitchen-vagrant-1.1.0/templates/Vagrantfile.erb"
      vagrantfiles: []
      vm_hostname: default-centos-7.vagrantup.com
    provisioner:
      additional_copy_path:
      - spec/fixtures/kitchen/roles/RHEL7-STIG/tasks
      - spec/fixtures/kitchen/roles/RHEL7-STIG/vars
      - spec/fixtures/inspec_profiles
      - spec/fixtures/inspec_profiles/CentOS-7-disa_stig
      - spec/fixtures/inspec_profiles/RedHat-7-disa_stig
      additional_copy_role_path: true
      additional_ssh_private_keys:
      ansible_apt_repo: ppa:ansible/ansible
      ansible_cfg_path:
      ansible_check: false
      ansible_connection: local
      ansible_diff: false
      ansible_host_key_checking: true
      ansible_inventory:
      ansible_inventory_file:
      ansible_limit:
      ansible_omnibus_remote_path: "/opt/ansible"
      ansible_omnibus_url: https://raw.githubusercontent.com/neillturner/omnibus-ansible/master/ansible_install.sh
      ansible_platform: ''
      ansible_playbook_command:
      ansible_sles_repo: http://download.opensuse.org/repositories/systemsmanagement/SLE_12/systemsmanagement.repo
      ansible_source_rev:
      ansible_source_url: git://github.com/ansible/ansible.git
      ansible_sudo: true
      ansible_vault_password_file:
      ansible_verbose: true
      ansible_verbosity: 2
      ansible_version: latest
      ansible_yum_repo: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      ansiblefile_path:
      callback_plugins_path:
      chef_bootstrap_url: https://www.getchef.com/chef/install.sh
      command_prefix:
      copy_symlinks: true
      custom_post_install_command:
      custom_post_play_command:
      custom_pre_install_command:
      custom_pre_play_command:
      enable_yum_epel: false
      env_vars: {}
      extra_vars: {}
      extra_vars_file:
      filter_plugins_path:
      ftp_proxy:
      group_vars_path:
      host_vars_path: "/tmp/kitchen/host_vars"
      hosts: all
      http_proxy:
      https_proxy:
      idempotency_test:
      ignore_extensions_from_root:
      - ".pyc"
      ignore_paths_from_root: []
      kerberos_conf_file:
      kitchen_root: "/Users/aaronl/Desktop/hardening/aaronlippold/inspec_profiles"
      library_plugins_path:
      lookup_plugins_path:
      max_retries: 1
      modules_path:
      name: ansible_playbook
      no_proxy:
      playbook: "/Users/aaronl/Desktop/hardening/aaronlippold/inspec_profiles/default.yml"
      python_sles_repo: http://download.opensuse.org/repositories/devel:/languages:/python/SLE_12/devel:languages:python.repo
      recursive_additional_copy_path:
      require_ansible_omnibus: false
      require_ansible_repo: true
      require_ansible_source: false
      require_chef_for_busser: false
      require_pip: false
      require_ruby_for_busser: false
      require_windows_support: false
      requirements_path: false
      retry_on_exit_code: []
      role_name: rhel7-stig
      roles_path: spec/fixtures/kitchen/roles
      root_path: "/tmp/kitchen"
      shell_command: sh
      ssh_known_hosts:
      sudo: true
      sudo_command: sudo -E
      tags: []
      test_base_path: "/Users/aaronl/Desktop/hardening/aaronlippold/inspec_profiles/test/integration"
      update_package_repos: true
      wait_for_retry: 30
    transport:
      compression: false
      compression_level: 0
      connection_retries: 5
      connection_retry_sleep: 1
      connection_timeout: 15
      keepalive: true
      keepalive_interval: 60
      kitchen_root: "/Users/aaronl/Desktop/hardening/aaronlippold/inspec_profiles"
      log_level: :info
      max_ssh_sessions: 6
      max_wait_until_ready: 600
      name: ssh
      port: 22
      ssh_gateway:
      ssh_gateway_username:
      ssh_key:
      test_base_path: "/Users/aaronl/Desktop/hardening/aaronlippold/inspec_profiles/test/integration"
      username: root
    verifier:
      chef_omnibus_root: "/opt/chef"
      command_prefix:
      ftp_proxy:
      http_proxy:
      https_proxy:
      inspec_tests:
      - file:///Users/aaronl/Desktop/hardening/aaronlippold/inspec_profiles/profiles/disa_stig-rhel7-baseline
      kitchen_root: "/Users/aaronl/Desktop/hardening/aaronlippold/inspec_profiles"
      log_level: :info
      name: inspec
      root_path: "/tmp/verifier"
      sudo: true
      sudo_command: sudo -E
      suite_name: default
      test_base_path: "/Users/aaronl/Desktop/hardening/aaronlippold/inspec_profiles/test/integration"
```
`.kitchen.ansible.yml`
```
driver:
  name: vagrant
  customize:
    natdnsproxy1: 'on'
    natdnshostresolver1: 'on'

provisioner:
  hosts: all
  name: ansible_playbook
  roles_path: spec/fixtures/kitchen/roles
  host_vars_path: /tmp/kitchen/host_vars
  role_name: rhel7-stig
  require_ruby_for_busser: false
  require_chef_for_busser: false
  require_ansible_repo: true
  ansible_verbose: true
  copy_symlinks: true
  additional_copy_role_path: true
  #ignore_paths_from_root: true
  #ansible_inventory: inventory/hosts_vagrant
  ansible_version: latest
  ansible_yum_repo: "http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
  ansible_verbosity: 2
  additional_copy_path:
    - spec/fixtures/kitchen/roles/RHEL7-STIG/tasks
    - spec/fixtures/kitchen/roles/RHEL7-STIG/vars
    - spec/fixtures/inspec_profiles
    - spec/fixtures/inspec_profiles/CentOS-7-disa_stig
    - spec/fixtures/inspec_profiles/RedHat-7-disa_stig
  https_proxy: <%= ENV['https_proxy'] %>

transport:
  max_ssh_sessions: 6

verifier:
  name: inspec
  sudo: true

platforms:
  - name: centos-7
    driver:
      box: centos/7

suites:
  - name: default
    verifier:
      inspec_tests:
        # if you want to use your local code
        - file://<%= ENV[('PWD')] %>/profiles/disa_stig-rhel7-baseline
        # if you want to use the current profile in the git repo
        #- git: https://github.com/<...>-baseline.git
      #controls:
      #  - V-72309
     #attrs:
     #  - attributes.yml
```
