### ISSUE TITLE
No such file for hosts

### ISSUE THREAD

**Issue by howdoicomputer** [neillturner/kitchen-ansible#256]
```
       Transferring files to <default-centos-7>
/home/howdoicomputer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/net-scp-1.2.1/lib/net/scp/upload.rb:117:in `stat': No such file or directory @ rb_file_s_stat - /tmp/default-centos-7-sandbox-20170905-24387-n7if0x/hosts (Errno::ENOENT)
        from /home/howdoicomputer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/net-scp-1.2.1/lib/net/scp/upload.rb:117:in `set_current'
        from /home/howdoicomputer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/net-scp-1.2.1/lib/net/scp/upload.rb:24:in `upload_start_state'

```

```
[~/w/w/packer-container-host-ecs]─[⎇ master]─[±]─(1)-> cat .kitchen.yml
---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  roles_path: cm/ansible/roles
  playbook: cm/ansible/playbook.yml
  hosts: all
  ansible_verbose: true
  ansible_version: latest
  require_ansible_repo: false
  require_chef_for_busser: false
  require_ruby_for_busser: false

transport:
  max_ssh_sessions: 6

verifier:
  name: inspec
  sudo_path: true

platforms:
  - name: centos-7

suites:
  - name: default
```

I'm able to manually create a hosts file:

```
[~/w/w/packer-container-host-ecs]─[⎇ master]─[±]─> mkdir /tmp/default-centos-7-sandbox-20170905-24387-n7if0x/
[~/w/w/packer-container-host-ecs]─[⎇ master]─[±]─> touch /tmp/default-centos-7-sandbox-20170905-24387-n7if0x/hosts
```

But when I re-run the verify step I get this:

```
E, [2017-09-05T23:06:19.180012 #28891] ERROR -- default-centos-7: ---Nested Exception---
E, [2017-09-05T23:06:19.180022 #28891] ERROR -- default-centos-7: Class: Kitchen::Transport::SshFailed
E, [2017-09-05T23:06:19.180032 #28891] ERROR -- default-centos-7: Message: SCP upload failed (open failed (1))
E, [2017-09-05T23:06:19.180042 #28891] ERROR -- default-centos-7: ----------------------
E, [2017-09-05T23:06:19.180052 #28891] ERROR -- default-centos-7: ------Backtrace-------
E, [2017-09-05T23:06:19.180063 #28891] ERROR -- default-centos-7: /home/howdoicomputer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/base.rb:83:in `rescue in call'
```

**Comment by howdoicomputer** [comment]
Also, is there a working example somewhere?

**Comment by neillturner** [comment]
i will add some docs for hosts today

**Comment by neillturner** [comment]
i guess you were looking at: 
  http://ansible.pickle.io/post/86598332429/running-ansible-playbook-in-localhost
 where the playbook is:
helloworld.yml
```yaml
---
- hosts: all
  tasks:
    - shell: echo "hello world"
```
you need to specify in the  .kitchen.yml 
```yaml
hosts: localhost 
 ```
