### ISSUE TITLE
Need boto modules in debian for ec2.py

### ISSUE THREAD

**Issue by MTN-RowinAndruscavage** [neillturner/kitchen-ansible#260]
Hello!  Let me know if there's a better way to make pull requests against the ansible_install.sh script at:
https://raw.githubusercontent.com/neillturner/omnibus-ansible/master/ansible_install.sh

This is a bit of an edge case, but we need the python-boto module set up in debian/ubuntu boxes.  Here's the diff against what's in your current ansible_omnibus_url
https://gist.github.com/MTN-RowinAndruscavage/139af7b2afcff4cff09a44b2efc40ef4/revisions

We're using ansible's dynamic_inventory.py to feed vars to our test VMs... which includes ec2.py for instances in AWS.  This is useful for testing stuff like e.g. monitoring boxes, which need to read vars from everything defined in ansible-inventory .

As an aside, it was a bit tricky to set up test-kitchen so it could allow this, but it was possible thanks to all of your documented options in provisioner_options.md !  There are a few strange things I ended up having to do in .kitchen.yml to get it to work, but it does work, so thank you for make ansible-kitchen flexible enough to handle this:

```
provisioner:
  # "none" means use inventory defined in ansible.cfg
  ansible_inventory: none

  # copy of normal ansible.cfg with full path to dynamic-inventory script:
  #   inventory      = /tmp/kitchen/ansible-inventory/scripts/dynamic_inventory.py
  ansible_cfg_path: /tmp/kitchen/ansible_kitchen.cfg

  additional_copy_path:
    - ansible_kitchen.cfg
    - boto   # copy of ~/.boto credentials to use to run ec2.py

  # maybe overkill, but I really want to make sure ansible uses these:
  env_vars:
    ANSIBLE_CONFIG: /tmp/kitchen/ansible_kitchen.cfg
    BOTO_CONFIG: /tmp/kitchen/boto

  recursive_additional_copy_path:
    - ansible-inventory


suites:
  # Can define "myapp-test" host in custom ansible-inventory to let it inherit group vars
  # or just specify all of the extra_vars here
  - name: myapp-test
    provisioner:
      playbook: site.yml
      hosts: myapp-test
      # make sure test-kitchen doesn't run against everything in inventory
      ansible_limit: myapp-test
```

Maybe some of those workarounds aren't necessary anymore, but just wanted to document what I had and let you know that people are using it!
