### ISSUE TITLE
How to test multiple playbooks

### ISSUE THREAD

**Issue by soupdiver** [neillturner/kitchen-ansible#27]
I'm new to the world of test-kitchen and so maybe my question goes in a wrong direction.
I've got a repository which includes all the different playbooks describing my infrastructure.
I've created a `.kitchen.yml` file which looks like

```yaml
---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  playbook: docker_registry.yml
  ansible_verbose: false
  hosts: docker_registry
  ansible_verbosity: 4

platforms:
  - name: ubuntu-12.04
    driver_config:
      box: ubuntu/precise64
  - name: ubuntu-14.04
    driver_config:
       box: ubuntu/trusty64

suites:
  - name: docker-registry
```

I also created some `Serverspec` tests at `test/integration/docker_registry/docker_spec.rb`. I can run my test suite as expected.
I've got another playbook called `nginx`. How would I add another suite and play the `nginx` playbook instead `docker_registry`?

**Comment by neillturner** [comment]
basically you create multiple suites: 
---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook

platforms:
  - name: ubuntu-12.04
    driver_config:
      box: ubuntu/precise64
  - name: ubuntu-14.04
    driver_config:
       box: ubuntu/trusty64

suites:
  - name: docker-registry
    provisioner:
       name: ansible_playbook
       playbook: docker_registry.yml
       ansible_verbose: false
       hosts: docker_registry
       ansible_verbosity: 4

  - name: nginx
    provisioner:
       name: ansible_playbook
       playbook: nginx.yml
       ansible_verbose: false
       hosts: nginx
       ansible_verbosity: 4

**Comment by soupdiver** [comment]
Ah cool, I didn't know that I could easily put the provisioner in the suites section. It looked as the provisioner would be global for all suites.
Maybe a hint in the Readme would be nice.

**Comment by trinitronx** [comment]
@soupdiver:  Yes, this is one of the great hidden features of test-kitchen!   You can add in suite or platform specific config settings, and usually test-kitchen will take them, [automagically merge][6] the Ruby hashes correctly, and use them!

For example... Let's say I want to use [`kitchen-ec2`][5] with some ec2-driver specific settings only on Amazon Linux platform:


```
platforms:
  - name: amazon-2014.09-east
    driver_plugin: ec2
    driver:
      image_id: ami-886ed3e0
      username: ec2-user
      availability_zone: us-east-1b
      flavor_id: c3.large
      aws_ssh_key_id: rp-maelstrom
      associate_public_ip: true
```

Note that this is assuming you've already set up your AWS keys in `driver_config:` up above:

```
driver_config:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  ssh_key: <%= ENV['KITCHEN_EC2_SSH_KEY'] %>
```

One of the oddities of test-kitchen however is that sometimes `.kitchen.yml` hash keys are not standard across all drivers.  I'll leave it at that since I can't remember the inconsistencies off the top of my head.  However, there are some other ways of getting around this...

You can also store [Driver-Specific][3] settings in an alternate `.kitchen.local.yml`, or `.kitchen.cloud.yml` file.  `.kitchen.local.yml` is [automatically used][1] by default in `test-kitchen` and merged.  This can be useful for storing local settings (for example with `kitchen-docker`) for fast local tests.

Or, you can store cloud-specific driver settings in the `.kitchen.cloud.yml` file for separating out [alternate cloud driver settings][2].  You can see this [pattern followed][4] in many OpsCode/Chef & Community Cookbooks.

[1]: https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/loader/yaml.rb#L56-L61
[2]: http://stackoverflow.com/questions/26516373/alternate-drivers-with-test-kitchen
[3]: https://docs.chef.io/config_yml_kitchen.html#driver-specific-settings
[4]: https://github.com/rackspace-cookbooks/mariadb/blob/master/.kitchen.cloud.yml
[5]: https://github.com/test-kitchen/kitchen-ec2
[6]: https://github.com/test-kitchen/test-kitchen/blob/master/spec/kitchen/loader/yaml_spec.rb#L118
