### ISSUE TITLE
Can't connect with ansible_inventory but no problems without it

### ISSUE THREAD

**Issue by TemporarilyOffline** [neillturner/kitchen-ansible#283]
I'm not 100% sure what is going on here, but I've been happily developing a playbook and got to a point where I wanted to deal with some inventory control methods.  I've been converging, verifying and destroying happily up until this point.

When I added in the controls for the inventory test-kitchen doesn't want to connect to the Vagrant box anymore.  If I remove those controls kitchen and vagrant are best buddies again.

I'm most likely missing something in the .kitchen.yml file, but I don't know what.

I'm trying to run a `when: inventory_hostname in groups['sacred_hosts']` in a command module definition.

Can you help out?

ansible_inventory.txt
```
% cat ansible_inventory.txt
[sacred_hosts]
localhost:2222
```

.kitchen.yml:
```
---
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 8192

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  ansible_vault_password_file: ../ansible_vault_password
  require_chef_ominbus: false
  require_chef_for_busser: true
  ansible_connection: ssh
  ansible_inventory: ansible_inventory.txt
  ansible_host_key_checking: false
  additional_copy_path:
    - ./lib
    - ./templates
    - ./vault

transport:
  max_ssh_sessions: 6

platforms:
   - name: ubuntu-16.04

suites:
  - name: default
    provisioner:
      name: ansible_playbook
      playbook: deploy.yml
```

Output with ansible_inventory:
```
-----> Starting Kitchen (v1.23.2)
-----> Converging <default-ubuntu-1604>...
       Preparing files for transfer
       Preparing playbook
       Preparing inventory
       Preparing modules
       nothing to do for modules
       Preparing roles
       Preparing ansible.cfg file
       Empty ansible.cfg generated
       Preparing group_vars
       nothing to do for group_vars
       Preparing additional_copy_path
       Copy additional path: ./lib
       Copy additional path: ./templates
       Copy additional path: ./vault
       Preparing host_vars
       nothing to do for host_vars
       Preparing spec
       nothing to do for spec
       Preparing library plugins
       nothing to do for library plugins
       Preparing callback plugins
       nothing to do for callback plugins
       Preparing filter_plugins
       nothing to do for filter_plugins
       Preparing lookup_plugins
       nothing to do for lookup_plugins
       Preparing ansible vault password
       Preparing additional_ssh_private_keys
       nothing to do for additional_ssh_private_keys
       Finished Preparing files for transfer
       Installing ansible, will try to determine platform os
       Transferring files to <default-ubuntu-1604>

       PLAY [all] *********************************************************************

       TASK [Gathering Facts] *********************************************************
       fatal: [localhost]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host localhost port 2222: Connection refused\r\n", "unreachable": true}
       	to retry, use: --limit @/tmp/kitchen/deploy.retry

       PLAY RECAP *********************************************************************
       localhost                  : ok=0    changed=0    unreachable=1    failed=0

>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-ubuntu-1604>.  Please see .kitchen/logs/default-ubuntu-1604.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

```
% ssh vagrant@localhost -p 2222
vagrant@localhost's password:
Welcome to Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-87-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

171 packages can be updated.
93 updates are security updates.


Last login: Wed Aug 15 18:27:00 2018 from 10.0.2.2
vagrant@default-ubuntu-1604:~$
```
