### ISSUE TITLE
Managing services make the playbook fail

### ISSUE THREAD

**Issue by Mallear** [neillturner/kitchen-ansible#285]
Hello,

I'm using `kitchen-ansible` and `kitchen-docker` to test my playbook with a docker container.
Every time it tries to run a task to stop or start a service, the execution fails.

Here is my `.kitchen.yml` file :

```
---
driver:
  name: docker
  use_sudo: false

platforms:
  - name: amazonlinux-2
    driver:
      image: n0ts/amazonlinux-ansible
      platform: centos

provisioner:
  name: ansible_playbook
  hosts: localhost
  roles_path: roles
  require_pip: true
  require_ansible_repo: false
  ansible_version: "2.6"
  require_chef_for_busser: false
  ansible_verbosity: 3

verifier:
  name: serverspec
  use_sudo: yes
  sudo_path: true

suites:
  - name: ldapadmin
    provisioner:
        name: ansible_playbook
        playbook: test/playbook.yml

```

Am I doing anything wrong or is this `kitchen-ansible` normal behavior ?
