### ISSUE TITLE
ansible_vault_password_file: is ignored

### ISSUE THREAD

**Issue by spuder** [neillturner/kitchen-ansible#289]
Trying to get kitchen-ansible working for the first time. Getting this error on converge

```
       ERROR! The vault password file /etc/ansible/keys/ansible-vault.key was not found
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-ubuntu-1604>.  Please see .kitchen/logs/default-ubuntu-1604.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

It appears that the way to change where the vault_password_file is set is in the .kitchen.yaml provisioners section

```
driver:
  name: vagrant
  # name: docker

provisioner:
  name: ansible_playbook
  roles_path: ansible/roles
  hosts: default-ubuntu-1604
  ansible_vault_password_file: ./keys/ansible-vault.key

platforms:
  - name: ubuntu-16.04
  # - name: centos-7

suites:
  - name: default
    run_list:
    attributes:

```

yet ansible_vault_password_file is ignored. Is this a bug or am I just doing it wrong?

**Comment by spuder** [comment]
For anyone else experiencing this, a workaround is to sync the /etc/ansible/keys directory
```
driver:
  name: vagrant
  synced_folders:
    - [ './keys', '/etc/ansible/keys']
```
