### ISSUE TITLE
Not working with kitchen-docker and amazonlinux docker image

### ISSUE THREAD

**Issue by ernjs** [neillturner/kitchen-ansible#290]
We're trying to setup kitchen using the [docker driver](https://github.com/test-kitchen/kitchen-docker) with [amazonlinux docker image](https://hub.docker.com/_/amazonlinux/), but this error keeps popping up:

`$ kitchen destroy && kitchen setup`

![image](https://user-images.githubusercontent.com/9384081/46374647-96e01880-c667-11e8-822a-6db0c5bf87c2.png)

It tries to use `apt-get` instead of yum, despite the fact that we explicitly configured to use the platform `rhel` (it doesn't work setting the platform to `centos`, too)

It's not possible to use the `kitchen-docker` along with `kithen-ansible`using the amazonlinux docker image? 

- kitchen.yml

```
---
verifier:
  name: inspec

driver:
  name: docker

provisioner:
  name: ansible_playbook
  hosts: amazon-docker
  
platforms:
  - name: amazon-docker
    driver_config:
      image: amazonlinux:latest
      platform: rhel

suites:
  - name: default
```
