### ISSUE TITLE
role not found issue

### ISSUE THREAD

**Issue by luckeyca** [neillturner/kitchen-ansible#333]
kitchen converge couldn't find the role to install with error below
```
       ERROR! the role 'ansible-role-ol9' was not found in /tmp/kitchen/roles:/tmp/kitchen/roles:/tmp/kitchen
       
       The error appears to be in '/tmp/kitchen/main.yml': line 5, column 7, but may
       be elsewhere in the file depending on the exact syntax problem.
       
       The offending line appears to be:
       
         roles:
           - role: ansible-role-ol9
             ^ here
```

config information as below:

1. gem package versions
```
# frozen_string_literal: true

source 'https://rubygems.org'
gem 'inspec', '5.22.72'
gem 'inspec-bin', '5.22.72'
gem 'inspec-core', '5.22.72'
gem 'kitchen-ansible', '0.56.0'
gem 'kitchen-ansiblepush', '0.11.0'
gem 'kitchen-docker', '3.0.0'
gem 'kitchen-docker_cli', '0.19.0'
gem 'kitchen-inspec', '3.0.0'
gem 'kitchen-oci', '1.27.0'
gem 'kitchen-terraform', '7.0.2'
gem 'kitchen-vagrant', '2.0.1'
gem 'test-kitchen', '3.7.0'
```

2. ansible role git repo directory structure
```
ansible-role-ol9
├── CHANGELOG.md
├── README.md
├── VERSION
├── azure-pipelines.yml
├── defaults
│   └── main.yml
├── files
│   └── README.md
├── handlers
│   └── main.yml
├── kitchen.yml
├── meta
│   └── main.yml
├── requirements.yml
├── tasks
│   └── main.yml
├── templates
│   └── README.md
├── test
│   ├── ansible.cfg
│   ├── fixtures
│   │   └── ansible-role-ol9-default
│   │       └── main.yml
│   ├── integration
│   │   ├── README.md
│   │   └── ansible-role-ol9-default
│   │       ├── controls
│   │       │   └── ansible-role-ol9-default.rb
│   │       └── inspec.yml
│   └── reports
│       └── README.md
└── vars
    └── main.yml
```

3. kitchen.yml
```
---
provisioner:
  name: ansible_playbook
  hosts: localhost
  require_chef_for_busser: false
  ansible_connection: local
  ansible_verbose: true
  ansible_diff: true
  ansible_verbosity: 2
  idempotency_test: true
  requirements_path: requirements.yml
  env_vars:
    OCI_REGION: <%= ENV['OCI_CLI_REGION'] %>
    OCI_USER_ID: <%= ENV['OCI_CLI_USER'] %>
    OCI_USER_FINGERPRINT: <%= ENV['OCI_CLI_FINGERPRINT'] %>
    OCI_USER_KEY_FILE: <%= ENV['OCI_CLI_KEY_FILE'] %>
    OCI_USER_KEY_PASS_PHRASE: <%= ENV['OCI_CLI_PASSPHRASE'] %>
    OCI_TENANCY: <%= ENV['OCI_CLI_TENANCY'] %>

driver:
  name: oci

platforms:
  - name: oracle-linux-9
    driver:
      compartment_id: <%= ENV['INSTANCE_COMPARTMENT_OCID'] %>
      availability_domain: <%= ENV['AVAILABILITY_DOMAIN'] %>
      image_id: <%= ENV['GOLDEN_IMAGE_OCID'] %>
      oci_config:
        region: <%= ENV['OCI_CLI_REGION'] %>
        user: <%= ENV['OCI_CLI_USER'] %>
        fingerprint: <%= ENV['OCI_CLI_FINGERPRINT'] %>
        key_file: <%= ENV['OCI_CLI_KEY_FILE'] %>
        pass_phrase: <%= ENV['OCI_CLI_PASSPHRASE'] %>
        tenancy: <%= ENV['OCI_CLI_TENANCY'] %>
      shape: <%= ENV['VM_SHAPE'] %>
      shape_config:
        ocpus: <%= ENV['VM_SHAPE_CONFIG_OCPU'] %>
        memory_in_gbs: <%= ENV['VM_SHAPE_CONFIG_MEMORY'] %>
      subnet_id: <%= ENV['INSTANCE_SUBNET_OCID'] %>
      use_private_ip: true
    transport:
      name: ssh
      username: opc
      ssh_key: /root/.ssh/id_rsa

verifier:
  name: inspec
  reporter:
    - cli
    - junit2:test/reports/%{platform}-%{suite}-inspec-junit.xml

suites:
  - name: ansible-role-ol9-default
    provisioner:
      playbook: test/fixtures/ansible-role-ol9-default/main.yml
```

4. test playbook: test/fixtures/ansible-role-ol9-default/main.yml
```
---
- hosts: localhost
  remote_user: opc
  roles:
    - role: ansible-role-ol9
```
