### ISSUE TITLE
Cannot place default.yml in test/integration/playbooks/default.yml

### ISSUE THREAD

**Issue by chris-rock** [neillturner/kitchen-ansible#41]
Current implementation does not seem to support files in `test/integration/playbooks/default.yml` as mentioned in https://github.com/neillturner/kitchen-ansible/blob/a458afa5fa5212fd1a95e7de371c8f0ac232c457/lib/kitchen/provisioner/ansible_playbook.rb#L55

**Comment by chris-rock** [comment]
as @rndmh3ro pointed out at hardening-io/tests-ssh-hardening/pull/46 this can be solved via:
```
suites:
- name: default
  roles_path: roles
  playbook: playbooks/default.yml
```
