### ISSUE TITLE
Unable to use Multiple playbooks based on documentation

### ISSUE THREAD

**Issue by evanccnyc** [neillturner/kitchen-ansible#79]
I followed the documentation here:

https://github.com/neillturner/kitchen-ansible#testing-multiple-playbooks

I get the following error:

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [unknown file type: rabbitmq]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

suites area looks like this:
```
suites:
  - name: rabbitmq
    provisioner:
      playbook: rabbitmq
      hosts: localhost
```

I tried both with rabbitmq.yml and rabbitmq both throw up the same error.

**Comment by trumant** [comment]
Running ```kitchen test --log-level=debug``` may help diagnose the issue more quickly.

Also, it would be helpful if you shared the directory structure you were using as well since I believe there are some strong constraints on how suite names map to paths under ```test/integration```

**Comment by trinitronx** [comment]
This is correct.. suite names and associated tests have a naming scheme based on the name of the suite.

For example, the default suite name is usually `default`.

So with this `.kitchen.yaml`:

```yaml
---
driver:
    name: vagrant

provisioner:
#  ansible_platform: ubuntu
  name: ansible_playbook
#  roles_path:
  hosts: test-kitchen
  require_ansible_repo: true
  ansible_verbose: true
  ansible_verbosity: 1
  sudo: true

platforms:
  # - name: ubuntu-10.04 # lucid
  - name: ubuntu-12.04 # precise
  - name: ubuntu-13.10 # saucy
  - name: ubuntu-14.04 # trusty
  - name: ubuntu-14.10 # utopic
  # - name: centos-5.10 # TODO: NOT TESTED YET... unsure if kitchen-ansible works yet...
  - name: centos-6.4
  - name: centos-6.5
  - name: centos-7.0
  # - name: nocm_centos-6.5
  #   driver_plugin: vagrant
  #   driver_config:
  #     box: nocm_centos-6.5
  #     box_url: http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-nocm.box
      # network:
      #  - ['forwarded_port', {guest: 8080, host: 8080}]
      #  - [ 'private_network', { ip: '192.168.33.11' } ]

suites:
  - name: default
  - name: dev
  - name: custompath
    provisioner:
      playbook: test/integration/my_custom_playbook_path.yml
```

This should be the directory structure:

```bash
~/src/ansible-playbooks/roles/altermn.rvm$ tree .
.
├── LICENSE
├── README.md
├── defaults
│   └── main.yml
├── meta
│   └── main.yml
├── tasks
│   ├── main.yml
│   ├── task_files_here.yml
│   └── etc...
└── test
    └── integration
        ├── default
        │   └── serverspec
        │       ├── rvm_spec.rb
        │       ├── more_serverspec_tests_here_spec.rb
        │       └── foo_spec.rb
        └── default.yml
        ├── dev
        │   └── serverspec
        │       └── foo_spec.rb
        └── dev.yml
        ├── custompath
        │   └── serverspec
        │       └── foo_spec.rb
        └── my_custom_playbook_path.yml
```

**Comment by neillturner** [comment]
A server can only run one top level file by fefault called default.yml

this can install multiple playbooks 
```yaml
# file: default.yml
- include: webservers.yml
- include: dbservers.yml
```

each of these can have multple roles. 
you can have tests either via serverspec in /test/integration....
or via ansiblespec where the tests are stored in the roles. 

closing
