### ISSUE TITLE
Running tests from multiple roles on one server?

### ISSUE THREAD

**Issue by phiche** [neillturner/kitchen-ansible#80]
I'm trying to run test-kitchen + serverspec provisioning with ansible on EC2. I have the basics running ok but not the way I want it.

What I want is to have tests within each role (fine if subfolder are called test/integration), but I want to be able to run all the tests for that role if I use that role in my playbook. 

So far, I haven't figured out how to do this and it's beginning to look like the current implementation only lets you run tests from a single folder for each suite you define? 

From the [test-kitchen documentation](https://docs.chef.io/config_yml_kitchen.html), if you're using chef, it looks like you can run tests from multiple cookbooks by defining the run_lists for each suite:

```
suites:
  - name: suite_name
    run_list:
      - recipe[cookbook_name::default]
      - recipe[another_cookbook_name::recipe_name]
````

Is there some specific folder structure that I need to do this, or alternatively is there some way I can explicitly specify which tests to run within each suite?
