### ISSUE TITLE
Ansible can't find the role

### ISSUE THREAD

**Issue by Seraf** [neillturner/kitchen-ansible#84]
Hello,

I'm using Docker provider and kitchen-ansible on jenkins.
Testing with `kitchen test` on my local computer works like a charm, but using it in jenkins fails : 
```
       Transferring files to <default-debian-wheezy>
       ERROR: cannot find role in /tmp/kitchen/roles/ansible-vault or /tmp/kitchen/ansible-vault or /tmp/kitchen/roles/ansible-vault
>>>>>> Converge failed on instance <default-debian-wheezy>.
>>>>>> Please see .kitchen/logs/default-debian-wheezy.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sudo -E ansible-playbook --inventory-file=/tmp/kitchen/hosts -c local -M /tmp/kitchen/modules -vv      /tmp/kitchen/default.yml]
>>>>>> ----------------------
```

On the docker instance : 
```
root@71c0a9dbb9ba:/var/lib/jenkins/docker/aufs/mnt/71c0a9dbb9bab0829ef517baf180befe6c6ce4d52b23913ea6d5f5597f806e93/tmp/kitchen# ls
ansible.cfg  default.yml  filter_plugins  group_vars  host_vars  hosts	lookup_plugins	modules  roles
root@71c0a9dbb9ba:/var/lib/jenkins/docker/aufs/mnt/71c0a9dbb9bab0829ef517baf180befe6c6ce4d52b23913ea6d5f5597f806e93/tmp/kitchen# cat ansible.cfg 
[defaults]
roles_path = /tmp/kitchen/roles
root@71c0a9dbb9ba:/var/lib/jenkins/docker/aufs/mnt/71c0a9dbb9bab0829ef517baf180befe6c6ce4d52b23913ea6d5f5597f806e93/tmp/kitchen# cd roles/
root@71c0a9dbb9ba:/var/lib/jenkins/docker/aufs/mnt/71c0a9dbb9bab0829ef517baf180befe6c6ce4d52b23913ea6d5f5597f806e93/tmp/kitchen/roles# ls
workspace
```

Here is my structure : 
```
jenkins@CI0-EU-WE1-PROD:~/jobs/ansible-vault/workspace$ tree
.
├── ansible.cfg
├── defaults
│   └── main.yml
├── handlers
│   └── main.yml
├── meta
│   └── main.yml
├── README.md
├── tasks
│   ├── bootstrap.yml
│   └── main.yml
├── templates
│   ├── vault.config.j2
└── test
    └── integration
        └── default
            └── default.yml
```

My `ansible.cfg` : 
```
[defaults]
roles_path = ../
```

My `.kitchen.yml` : 
```
---
driver:
  name: docker
  use_sudo: false

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  ansible_verbosity: 2
  ansible_verbose: true

platforms:
  - name: debian-wheezy
    driver_config:
      image: debian:wheezy-backports
      platform: debian

suites:
  - name: default
```

My `test/integration/default/default.yml` : 
```
- hosts: all
  roles:
    - ansible-vault
```

My jenkins jobs is setup with a shell script : 
```
#!/bin/bash
source /usr/local/rvm/scripts/rvm
kitchen test
```

I guess the problem is the **workspace** directory, but don't know how to deal with. Have you an idea please ?

On my computer, it works as expected

Thanks
